services:
  project_mgmt:
    build:
      context: .
      dockerfile: apps/project_mgmt/Dockerfile
    ports:
      - "127.0.0.1:8011:8011"
  billing:
    build:
      context: .
      dockerfile: apps/billing/Dockerfile
    ports:
      - "127.0.0.1:8012:8012"
