from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
BASELINE_REGISTRY = ROOT / "baselines" / "baseline-registry.json"
LEADERBOARD_SUBMISSIONS = ROOT / "leaderboard_submissions"
TASK_QUALITY_MATRIX = ROOT / "docs" / "task-quality-matrix.json"
EVIDENCE_MAP = ROOT / "docs" / "authzbench-saas-v0.0-evidence-map.md"
OUT_DIR = ROOT / "paper" / "shared"


def load_json(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        data = json.load(handle)
    if not isinstance(data, dict):
        raise TypeError(f"{path} must contain a JSON object")
    return data


def tex_escape(value: object) -> str:
    text = "n/a" if value is None else str(value)
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    return "".join(replacements.get(char, char) for char in text)


def rate(value: object) -> str:
    if value is None:
        return "n/a"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return f"{float(value):.4g}"
    return str(value)


def read_summary(summary_path: str) -> dict[str, Any]:
    path = ROOT / "baselines" / summary_path
    return load_json(path)


def release_snapshot_baseline_ids(registry: dict[str, Any], snapshot_id: str = "v0.0") -> set[str]:
    for snapshot in registry.get("release_snapshots", []):
        if isinstance(snapshot, dict) and snapshot.get("id") == snapshot_id:
            baseline_ids = snapshot.get("baseline_ids")
            if isinstance(baseline_ids, list):
                return {str(item) for item in baseline_ids}
    return set()


def public_baseline_rows(registry: dict[str, Any]) -> list[list[str]]:
    rows: list[list[str]] = []
    snapshot_ids = release_snapshot_baseline_ids(registry)
    for entry in registry["baselines"]:
        if snapshot_ids:
            if entry.get("id") not in snapshot_ids:
                continue
        elif entry.get("release_suitability") not in {
            "current_public_harness_check",
            "current_public_split",
        }:
            continue
        artifacts = entry.get("run_artifacts") or [entry["summary_path"]]
        for index, artifact in enumerate(artifacts, start=1):
            summary = read_summary(str(artifact))
            label = summary.get("model", entry.get("id", "unknown"))
            if len(artifacts) > 1:
                label = f"{label} run {index}"
            if entry.get("kind") == "harness_check":
                label = "Scripted sanity baseline"
            if snapshot_ids:
                label = f"{label} (v0.0)"
            rows.append(
                [
                    tex_escape(label),
                    tex_escape(summary.get("harness_type")),
                    str(summary.get("task_count")),
                    str(summary.get("v0_passed_count", summary.get("passed_count"))),
                    rate(summary.get("exploit_proven_success_rate")),
                    rate(summary.get("boundary_reasoning_pass_rate")),
                    rate(summary.get("false_positive_rate")),
                    rate(summary.get("authorized_allow_pass_rate")),
                    rate(summary.get("target_request_coverage_rate")),
                ]
            )
    return rows


def write_baseline_table(registry: dict[str, Any]) -> None:
    rows = public_baseline_rows(registry)
    lines = [
        "% Generated by scripts/generate_paper_tables.py; do not hand edit.",
        r"\footnotesize",
        r"\begin{tabular}{@{}llrrrrrrr@{}}",
        r"\toprule",
        "Baseline & Harness & Tasks & V0 pass & Exploit & Boundary & FP & Allow & Requests \\\\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(row) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    (OUT_DIR / "baseline-table.tex").write_text("\n".join(lines), encoding="utf-8")


def write_task_mix_table(matrix: dict[str, Any]) -> None:
    rows: list[list[str]] = []
    for app, counts in sorted(matrix["apps"].items()):
        rows.append(
            [
                tex_escape(app.replace("_", " ")),
                str(counts["task_count"]),
                str(counts["vulnerable_task_count"]),
                str(counts["control_task_count"]),
                str(counts["denial_control_task_count"]),
                str(counts["authorized_allow_control_task_count"]),
                str(counts.get("workflow_evidence_task_count", 0)),
            ]
        )
    summary = matrix["summary"]
    rows.append(
        [
            r"\textbf{Total}",
            str(summary["task_count"]),
            str(summary["vulnerable_task_count"]),
            str(summary["control_task_count"]),
            str(summary["denial_control_task_count"]),
            str(summary["authorized_allow_control_task_count"]),
            str(summary.get("workflow_evidence_task_count", 0)),
        ]
    )
    lines = [
        "% Generated by scripts/generate_paper_tables.py; do not hand edit.",
        r"\scriptsize",
        r"\begin{tabular}{@{}lrrrrrr@{}}",
        r"\toprule",
        "Family & Tasks & Vuln. & Ctrl. & Deny & Allow & Flow \\\\",
        r"\midrule",
    ]
    for row in rows[:-1]:
        lines.append(" & ".join(row) + r" \\")
    lines.append(r"\midrule")
    lines.append(" & ".join(rows[-1]) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    (OUT_DIR / "task-mix-table.tex").write_text("\n".join(lines), encoding="utf-8")


def count_evidence_rows(markdown: str, heading: str) -> int:
    pattern = re.compile(rf"^## {re.escape(heading)}\n(?P<body>.*?)(?:\n## |\Z)", re.S | re.M)
    match = pattern.search(markdown)
    if not match:
        return 0
    body = match.group("body")
    return sum(1 for line in body.splitlines() if line.startswith("| ") and not line.startswith("| ---"))


def leaderboard_counts() -> tuple[int, int]:
    total = 0
    eligible = 0
    for path in sorted(LEADERBOARD_SUBMISSIONS.glob("**/*.json")):
        data = load_json(path)
        total += 1
        if data.get("leaderboard_eligible") is True:
            eligible += 1
    return total, eligible


def write_evidence_map_table(
    registry: dict[str, Any],
    matrix: dict[str, Any],
    evidence_markdown: str,
) -> None:
    supported = count_evidence_rows(evidence_markdown, "Supported Claims")
    partial = count_evidence_rows(evidence_markdown, "Partially Supported Claims")
    unsupported = count_evidence_rows(evidence_markdown, "Unsupported Claims")
    snapshot_ids = release_snapshot_baseline_ids(registry)
    snapshot_entries = [entry for entry in registry["baselines"] if entry.get("id") in snapshot_ids]
    current_entries = [
        entry
        for entry in registry["baselines"]
        if entry.get("release_suitability")
        in {"current_public_harness_check", "current_public_split"}
    ]
    total_submissions, eligible_submissions = leaderboard_counts()
    summary = matrix["summary"]
    rows = [
        [
            "Public split",
            "Supported",
            f"{summary['task_count']} tasks; {summary['vulnerable_task_count']} vulnerable; {summary['control_task_count']} controls",
        ],
        [
            "V0.0 release snapshot baselines",
            "Supported",
            f"{len(snapshot_entries or current_entries)} registry entries; current v1 reruns pending",
        ],
        [
            "Private leaderboard-candidate rows",
            "Partially supported",
            f"{eligible_submissions} eligible of {total_submissions} tracked submissions; not hosted leaderboard operation",
        ],
        [
            "Evidence-map claim ledger",
            "Mixed",
            f"{supported} supported; {partial} partial; {unsupported} unsupported rows",
        ],
    ]
    lines = [
        "% Generated by scripts/generate_paper_tables.py; do not hand edit.",
        r"\scriptsize",
        r"\begin{tabular}{@{}p{0.26\columnwidth}p{0.17\columnwidth}p{0.47\columnwidth}@{}}",
        r"\toprule",
        "Area & Status & Generated evidence \\\\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(tex_escape(item) for item in row) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", ""])
    (OUT_DIR / "evidence-map-table.tex").write_text("\n".join(lines), encoding="utf-8")


def write_macros(matrix: dict[str, Any]) -> None:
    summary = matrix["summary"]
    lines = [
        "% Generated by scripts/generate_paper_tables.py; do not hand edit.",
        r"\newcommand{\benchmarkname}{AuthZBench-SaaS}",
        r"\newcommand{\releaseversion}{v1-prep draft}",
        rf"\newcommand{{\publictaskcount}}{{{summary['task_count']}}}",
        r"\newcommand{\publicappcount}{6}",
        rf"\newcommand{{\vulnerabletaskcount}}{{{summary['vulnerable_task_count']}}}",
        rf"\newcommand{{\securecontrolcount}}{{{summary['control_task_count']}}}",
        rf"\newcommand{{\denialcontrolcount}}{{{summary['denial_control_task_count']}}}",
        rf"\newcommand{{\authorizedallowcount}}{{{summary['authorized_allow_control_task_count']}}}",
        "",
    ]
    (OUT_DIR / "authzbench-macros.tex").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    registry = load_json(BASELINE_REGISTRY)
    matrix = load_json(TASK_QUALITY_MATRIX)
    evidence_markdown = EVIDENCE_MAP.read_text(encoding="utf-8")
    write_macros(matrix)
    write_baseline_table(registry)
    write_task_mix_table(matrix)
    write_evidence_map_table(registry, matrix, evidence_markdown)


if __name__ == "__main__":
    main()
